name: example
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.24.0-7.0 <2.0.0'

dependencies:
  path_drawing:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
