name: path_drawing
version: 0.5.0-nullsafety.0
description: >
  A flutter library to help with (Canvas) Path creation and manipulation
homepage: https://github.com/dnfield/flutter_path_drawing

dependencies:
  vector_math: ^2.1.0-nullsafety.3
  meta: ^1.3.0-nullsafety.4
  path_parsing: ^0.2.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  path: ^1.8.0-nullsafety.1
  test: ^1.16.0-nullsafety.9
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # There's no need to include these as we don't use them.
  # This fixes an issue when our plugin is imported into a project that also
  # uses no material icons.
  uses-material-design: false

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.24.0-7.0 <2.0.0'
